#!/usr/bin/perl -w
#
# This script reads in a list of BSV files (provided by another tool) and creates
# a build directory, including appropiate sym links and Makefile.
#

use strict "vars";
use warnings;
no  warnings("once");
use File::Spec;
use File::Spec::Unix;

#--------------------------------------------------------------------------
# Command line processing
#--------------------------------------------------------------------------


sub ERROR
{
  my ( $msg ) = @_;
  print "\n ERROR: $msg \n\n";
  exit;
}


sub makeMakefile
{
  my $mods = $_[0];
  return "XXX Write this";
}

sub main()
{

  #Something might need to be done here with relative paths
  
  
  # Create simlinks
  
  foreach my $modloc (@ARGV)
  {
    my ($volume, $directories, $mod) = File::Spec->splitpath( $modloc );
  
    `ln -s $modloc`;
    if ($? != 0)
    {
      ERROR("Error creating symlink from $modloc to $mod");
    }
  }
  # Create Makefile
  
  my $makefile = makeMakefile(@ARGV);
  
  open(MFILE, ">Makefile") or ERROR("Could not create Makefile");
  print MFILE $makefile;
  close(MFILE);
  
}

main();
