#!/usr/bin/env perl
# -*- perl -*-

# benchmark run script generated by <<<SCRIPT>>>

use Getopt::Long;

#
# Turn on warnings
#
$^W = 1;

# command options
my $cycles = 800000;
my $instructions = 800000;

my $events = 0;
my $events_start = undef;
my $events_end = undef;

my $trace = 0;
my $trace_start = undef;
my $trace_end = undef;

my $debug = 0;
my $help = 0;

my $status;

$status = GetOptions( "c=s"         => \$cycles,
		      "i=s"         => \$instructions,
                      "t!"          => \$trace,
                      "tsc=s"       => \$trace_start,
                      "tec=s"       => \$trace_end,
                      "e!"          => \$events,
                      "esc=s"       => \$events_start,
                      "eec=s"       => \$events_end,
                      "debug"       => \$debug,
                      "help"        => \$help
		      );

if (!$status) {
  print "Switch parse failure\n";
  exit 0;
}

if ($debug) {
  print "Cycles = $cycles\n";
}

my $command = "<<<PROGRAM>>>";

if ( $command =~ /simv/) {
   # Direct simulation arguments
   $args="+max-cycles=$cycles";
 } else {
   # Hybrid simulation arguments
   $args="";
 }

print "Running: $command\n";
$status = system("$command $args | tee <<<BENCHMARK>>>.out");
print "Status: $status\n";
