#!/bin/sh

##############################################################
#
# Benchmark setup for bluespec design
#
# Usage: setup-bmark-smips <srcdir> <destdir> <bmark>
#
# Setup benchmark to run in <destdir> 
#
##############################################################


# 1. Build Benchmark in $destdir
# 2. Create $destdir/run

if [ $# -ne 3 ]; then
   echo Usage $0 "<srcdir> <destdir> <bmark>"
   echo $*
   exit 1
fi

srcdir=$1
destdir=$2
bmark=$3

# echo "BMARK: $bmark"
# echo "SRC: $srcdir"
# echo "DST: $destdir"

echo "Go to $destdir"
cd $destdir

echo "Creating simlinks"
mkdir -p program

/bin/ln -f -s ../../pm/simv .
/bin/ln -f -s ../../pm/simv.daidir

#
# Create run script with variable substition on run template
#    Note: we can't substitute strings with a * in them

echo "Creating run script"
sed "s*<<<SCRIPT>>>*$0*" <$srcdir/run.pl | sed "s*<<<BENCHMARK>>>*$bmark*" >run

chmod +x run

exit 0
